### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by Nick-Mazuk** [finale-lua/pdk-framework-docs#7]
Not sure where the best place is to report this, but there's a small typo in the generated PDK docs:

```
Seturns the shape ID for the MM rest
```

Should be

```
Sets the shape ID for the MM rest
```

https://pdk.finalelua.com/class_f_c_multi_measure_rest_prefs.html#a295dfee311f547b6b33aa4f0ff984b31

**Comment by rpatters1** [comment]
I'll fix it in the PDK Framework source code and it will appear with the next release of RGP Lua.

**Comment by rpatters1** [comment]
Will go up with next release of RGP Lua.
