### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/pdk-framework-docs#8]
I would like to rename this repository to somthing like `pdk-framework-docs`. Will that break anything about how it automatically publishes to the website?

@Nick-Mazuk

**Comment by Nick-Mazuk** [comment]
I don't think so?

If it does, it's an easy fix on my end.

In case you're worried, I reached out to support and should hear back within a day or two to know for sure. Though feel free to change the name before then.

I do support this repo name change. It definitely describes the intent of this repo much better.

**Comment by Nick-Mazuk** [comment]
Vercel said this will not be an issue so I'll go ahead and change the repo name.

**Comment by Nick-Mazuk** [comment]
I can confirm that after changing the name, everything is still hooked up with Vercel so I don't anticipate any issues. Closing this issue. Feel free to reopen if you notice issues in the future.
